export interface Country {
  name: string;
  code: string;
  phoneCode: string;
  phoneLength: number[];
  flag: string;
}

export const countries: Country[] = [
  { name: 'Afghanistan', code: 'AF', phoneCode: '+93', phoneLength: [9], flag: '🇦🇫' },
  { name: 'Albania', code: 'AL', phoneCode: '+355', phoneLength: [9], flag: '🇦🇱' },
  { name: 'Algeria', code: 'DZ', phoneCode: '+213', phoneLength: [9], flag: '🇩🇿' },
  { name: 'Andorra', code: 'AD', phoneCode: '+376', phoneLength: [6, 7], flag: '🇦🇩' },
  { name: 'Angola', code: 'AO', phoneCode: '+244', phoneLength: [9], flag: '🇦🇴' },
  { name: 'Antigua and Barbuda', code: 'AG', phoneCode: '+1', phoneLength: [10], flag: '🇦🇬' },
  { name: 'Argentina', code: 'AR', phoneCode: '+54', phoneLength: [10, 11], flag: '🇦🇷' },
  { name: 'Armenia', code: 'AM', phoneCode: '+374', phoneLength: [8], flag: '🇦🇲' },
  { name: 'Australia', code: 'AU', phoneCode: '+61', phoneLength: [9], flag: '🇦🇺' },
  { name: 'Austria', code: 'AT', phoneCode: '+43', phoneLength: [10, 11, 12], flag: '🇦🇹' },
  { name: 'Azerbaijan', code: 'AZ', phoneCode: '+994', phoneLength: [9], flag: '🇦🇿' },
  { name: 'Bahamas', code: 'BS', phoneCode: '+1', phoneLength: [10], flag: '🇧🇸' },
  { name: 'Bahrain', code: 'BH', phoneCode: '+973', phoneLength: [8], flag: '🇧🇭' },
  { name: 'Bangladesh', code: 'BD', phoneCode: '+880', phoneLength: [10, 11], flag: '🇧🇩' },
  { name: 'Barbados', code: 'BB', phoneCode: '+1', phoneLength: [10], flag: '🇧🇧' },
  { name: 'Belarus', code: 'BY', phoneCode: '+375', phoneLength: [9], flag: '🇧🇾' },
  { name: 'Belgium', code: 'BE', phoneCode: '+32', phoneLength: [9], flag: '🇧🇪' },
  { name: 'Belize', code: 'BZ', phoneCode: '+501', phoneLength: [7], flag: '🇧🇿' },
  { name: 'Benin', code: 'BJ', phoneCode: '+229', phoneLength: [8], flag: '🇧🇯' },
  { name: 'Bhutan', code: 'BT', phoneCode: '+975', phoneLength: [8], flag: '🇧🇹' },
  { name: 'Bolivia', code: 'BO', phoneCode: '+591', phoneLength: [8], flag: '🇧🇴' },
  { name: 'Bosnia and Herzegovina', code: 'BA', phoneCode: '+387', phoneLength: [8], flag: '🇧🇦' },
  { name: 'Botswana', code: 'BW', phoneCode: '+267', phoneLength: [8], flag: '🇧🇼' },
  { name: 'Brazil', code: 'BR', phoneCode: '+55', phoneLength: [10, 11], flag: '🇧🇷' },
  { name: 'Brunei', code: 'BN', phoneCode: '+673', phoneLength: [7], flag: '🇧🇳' },
  { name: 'Bulgaria', code: 'BG', phoneCode: '+359', phoneLength: [9], flag: '🇧🇬' },
  { name: 'Burkina Faso', code: 'BF', phoneCode: '+226', phoneLength: [8], flag: '🇧🇫' },
  { name: 'Burundi', code: 'BI', phoneCode: '+257', phoneLength: [8], flag: '🇧🇮' },
  { name: 'Cambodia', code: 'KH', phoneCode: '+855', phoneLength: [9], flag: '🇰🇭' },
  { name: 'Cameroon', code: 'CM', phoneCode: '+237', phoneLength: [9], flag: '🇨🇲' },
  { name: 'Canada', code: 'CA', phoneCode: '+1', phoneLength: [10], flag: '🇨🇦' },
  { name: 'Cape Verde', code: 'CV', phoneCode: '+238', phoneLength: [7], flag: '🇨🇻' },
  { name: 'Central African Republic', code: 'CF', phoneCode: '+236', phoneLength: [8], flag: '🇨🇫' },
  { name: 'Chad', code: 'TD', phoneCode: '+235', phoneLength: [8], flag: '🇹🇩' },
  { name: 'Chile', code: 'CL', phoneCode: '+56', phoneLength: [9], flag: '🇨🇱' },
  { name: 'China', code: 'CN', phoneCode: '+86', phoneLength: [11], flag: '🇨🇳' },
  { name: 'Colombia', code: 'CO', phoneCode: '+57', phoneLength: [10], flag: '🇨🇴' },
  { name: 'Comoros', code: 'KM', phoneCode: '+269', phoneLength: [7], flag: '🇰🇲' },
  { name: 'Congo', code: 'CG', phoneCode: '+242', phoneLength: [9], flag: '🇨🇬' },
  { name: 'Costa Rica', code: 'CR', phoneCode: '+506', phoneLength: [8], flag: '🇨🇷' },
  { name: 'Croatia', code: 'HR', phoneCode: '+385', phoneLength: [9], flag: '🇭🇷' },
  { name: 'Cuba', code: 'CU', phoneCode: '+53', phoneLength: [8], flag: '🇨🇺' },
  { name: 'Cyprus', code: 'CY', phoneCode: '+357', phoneLength: [8], flag: '🇨🇾' },
  { name: 'Czech Republic', code: 'CZ', phoneCode: '+420', phoneLength: [9], flag: '🇨🇿' },
  { name: 'Democratic Republic of the Congo', code: 'CD', phoneCode: '+243', phoneLength: [9], flag: '🇨🇩' },
  { name: 'Denmark', code: 'DK', phoneCode: '+45', phoneLength: [8], flag: '🇩🇰' },
  { name: 'Djibouti', code: 'DJ', phoneCode: '+253', phoneLength: [8], flag: '🇩🇯' },
  { name: 'Dominica', code: 'DM', phoneCode: '+1', phoneLength: [10], flag: '🇩🇲' },
  { name: 'Dominican Republic', code: 'DO', phoneCode: '+1', phoneLength: [10], flag: '🇩🇴' },
  { name: 'East Timor', code: 'TL', phoneCode: '+670', phoneLength: [8], flag: '🇹🇱' },
  { name: 'Ecuador', code: 'EC', phoneCode: '+593', phoneLength: [9], flag: '🇪🇨' },
  { name: 'Egypt', code: 'EG', phoneCode: '+20', phoneLength: [10], flag: '🇪🇬' },
  { name: 'El Salvador', code: 'SV', phoneCode: '+503', phoneLength: [8], flag: '🇸🇻' },
  { name: 'Equatorial Guinea', code: 'GQ', phoneCode: '+240', phoneLength: [9], flag: '🇬🇶' },
  { name: 'Eritrea', code: 'ER', phoneCode: '+291', phoneLength: [7], flag: '🇪🇷' },
  { name: 'Estonia', code: 'EE', phoneCode: '+372', phoneLength: [7, 8], flag: '🇪🇪' },
  { name: 'Eswatini', code: 'SZ', phoneCode: '+268', phoneLength: [8], flag: '🇸🇿' },
  { name: 'Ethiopia', code: 'ET', phoneCode: '+251', phoneLength: [9], flag: '🇪🇹' },
  { name: 'Fiji', code: 'FJ', phoneCode: '+679', phoneLength: [7], flag: '🇫🇯' },
  { name: 'Finland', code: 'FI', phoneCode: '+358', phoneLength: [9], flag: '🇫🇮' },
  { name: 'France', code: 'FR', phoneCode: '+33', phoneLength: [9], flag: '🇫🇷' },
  { name: 'Gabon', code: 'GA', phoneCode: '+241', phoneLength: [8], flag: '🇬🇦' },
  { name: 'Gambia', code: 'GM', phoneCode: '+220', phoneLength: [7], flag: '🇬🇲' },
  { name: 'Georgia', code: 'GE', phoneCode: '+995', phoneLength: [9], flag: '🇬🇪' },
  { name: 'Germany', code: 'DE', phoneCode: '+49', phoneLength: [10, 11, 12], flag: '🇩🇪' },
  { name: 'Ghana', code: 'GH', phoneCode: '+233', phoneLength: [9], flag: '🇬🇭' },
  { name: 'Greece', code: 'GR', phoneCode: '+30', phoneLength: [10], flag: '🇬🇷' },
  { name: 'Grenada', code: 'GD', phoneCode: '+1', phoneLength: [10], flag: '🇬🇩' },
  { name: 'Guatemala', code: 'GT', phoneCode: '+502', phoneLength: [8], flag: '🇬🇹' },
  { name: 'Guinea', code: 'GN', phoneCode: '+224', phoneLength: [9], flag: '🇬🇳' },
  { name: 'Guinea-Bissau', code: 'GW', phoneCode: '+245', phoneLength: [7], flag: '🇬🇼' },
  { name: 'Guyana', code: 'GY', phoneCode: '+592', phoneLength: [7], flag: '🇬🇾' },
  { name: 'Haiti', code: 'HT', phoneCode: '+509', phoneLength: [8], flag: '🇭🇹' },
  { name: 'Honduras', code: 'HN', phoneCode: '+504', phoneLength: [8], flag: '🇭🇳' },
  { name: 'Hungary', code: 'HU', phoneCode: '+36', phoneLength: [9], flag: '🇭🇺' },
  { name: 'Iceland', code: 'IS', phoneCode: '+354', phoneLength: [7], flag: '🇮🇸' },
  { name: 'India', code: 'IN', phoneCode: '+91', phoneLength: [10], flag: '🇮🇳' },
  { name: 'Indonesia', code: 'ID', phoneCode: '+62', phoneLength: [9, 10, 11], flag: '🇮🇩' },
  { name: 'Iran', code: 'IR', phoneCode: '+98', phoneLength: [10], flag: '🇮🇷' },
  { name: 'Iraq', code: 'IQ', phoneCode: '+964', phoneLength: [10], flag: '🇮🇶' },
  { name: 'Ireland', code: 'IE', phoneCode: '+353', phoneLength: [9], flag: '🇮🇪' },
  { name: 'Israel', code: 'IL', phoneCode: '+972', phoneLength: [9], flag: '🇮🇱' },
  { name: 'Italy', code: 'IT', phoneCode: '+39', phoneLength: [10, 11], flag: '🇮🇹' },
  { name: 'Ivory Coast', code: 'CI', phoneCode: '+225', phoneLength: [10], flag: '🇨🇮' },
  { name: 'Jamaica', code: 'JM', phoneCode: '+1', phoneLength: [10], flag: '🇯🇲' },
  { name: 'Japan', code: 'JP', phoneCode: '+81', phoneLength: [10], flag: '🇯🇵' },
  { name: 'Jordan', code: 'JO', phoneCode: '+962', phoneLength: [9], flag: '🇯🇴' },
  { name: 'Kazakhstan', code: 'KZ', phoneCode: '+7', phoneLength: [10], flag: '🇰🇿' },
  { name: 'Kenya', code: 'KE', phoneCode: '+254', phoneLength: [9], flag: '🇰🇪' },
  { name: 'Kiribati', code: 'KI', phoneCode: '+686', phoneLength: [8], flag: '🇰🇮' },
  { name: 'Kuwait', code: 'KW', phoneCode: '+965', phoneLength: [8], flag: '🇰🇼' },
  { name: 'Kyrgyzstan', code: 'KG', phoneCode: '+996', phoneLength: [9], flag: '🇰🇬' },
  { name: 'Laos', code: 'LA', phoneCode: '+856', phoneLength: [10], flag: '🇱🇦' },
  { name: 'Latvia', code: 'LV', phoneCode: '+371', phoneLength: [8], flag: '🇱🇻' },
  { name: 'Lebanon', code: 'LB', phoneCode: '+961', phoneLength: [8], flag: '🇱🇧' },
  { name: 'Lesotho', code: 'LS', phoneCode: '+266', phoneLength: [8], flag: '🇱🇸' },
  { name: 'Liberia', code: 'LR', phoneCode: '+231', phoneLength: [8], flag: '🇱🇷' },
  { name: 'Libya', code: 'LY', phoneCode: '+218', phoneLength: [9], flag: '🇱🇾' },
  { name: 'Liechtenstein', code: 'LI', phoneCode: '+423', phoneLength: [7], flag: '🇱🇮' },
  { name: 'Lithuania', code: 'LT', phoneCode: '+370', phoneLength: [8], flag: '🇱🇹' },
  { name: 'Luxembourg', code: 'LU', phoneCode: '+352', phoneLength: [6, 7], flag: '🇱🇺' },
  { name: 'Madagascar', code: 'MG', phoneCode: '+261', phoneLength: [9], flag: '🇲🇬' },
  { name: 'Malawi', code: 'MW', phoneCode: '+265', phoneLength: [9], flag: '🇲🇼' },
  { name: 'Malaysia', code: 'MY', phoneCode: '+60', phoneLength: [9, 10], flag: '🇲🇾' },
  { name: 'Maldives', code: 'MV', phoneCode: '+960', phoneLength: [7], flag: '🇲🇻' },
  { name: 'Mali', code: 'ML', phoneCode: '+223', phoneLength: [8], flag: '🇲🇱' },
  { name: 'Malta', code: 'MT', phoneCode: '+356', phoneLength: [8], flag: '🇲🇹' },
  { name: 'Marshall Islands', code: 'MH', phoneCode: '+692', phoneLength: [7], flag: '🇲🇭' },
  { name: 'Mauritania', code: 'MR', phoneCode: '+222', phoneLength: [8], flag: '🇲🇷' },
  { name: 'Mauritius', code: 'MU', phoneCode: '+230', phoneLength: [8], flag: '🇲🇺' },
  { name: 'Mexico', code: 'MX', phoneCode: '+52', phoneLength: [10], flag: '🇲🇽' },
  { name: 'Micronesia', code: 'FM', phoneCode: '+691', phoneLength: [7], flag: '🇫🇲' },
  { name: 'Moldova', code: 'MD', phoneCode: '+373', phoneLength: [8], flag: '🇲🇩' },
  { name: 'Monaco', code: 'MC', phoneCode: '+377', phoneLength: [8, 9], flag: '🇲🇨' },
  { name: 'Mongolia', code: 'MN', phoneCode: '+976', phoneLength: [8], flag: '🇲🇳' },
  { name: 'Montenegro', code: 'ME', phoneCode: '+382', phoneLength: [8], flag: '🇲🇪' },
  { name: 'Morocco', code: 'MA', phoneCode: '+212', phoneLength: [9], flag: '🇲🇦' },
  { name: 'Mozambique', code: 'MZ', phoneCode: '+258', phoneLength: [9], flag: '🇲🇿' },
  { name: 'Myanmar', code: 'MM', phoneCode: '+95', phoneLength: [9, 10], flag: '🇲🇲' },
  { name: 'Namibia', code: 'NA', phoneCode: '+264', phoneLength: [9], flag: '🇳🇦' },
  { name: 'Nauru', code: 'NR', phoneCode: '+674', phoneLength: [7], flag: '🇳🇷' },
  { name: 'Nepal', code: 'NP', phoneCode: '+977', phoneLength: [10], flag: '🇳🇵' },
  { name: 'Netherlands', code: 'NL', phoneCode: '+31', phoneLength: [9], flag: '🇳🇱' },
  { name: 'New Zealand', code: 'NZ', phoneCode: '+64', phoneLength: [9, 10], flag: '🇳🇿' },
  { name: 'Nicaragua', code: 'NI', phoneCode: '+505', phoneLength: [8], flag: '🇳🇮' },
  { name: 'Niger', code: 'NE', phoneCode: '+227', phoneLength: [8], flag: '🇳🇪' },
  { name: 'Nigeria', code: 'NG', phoneCode: '+234', phoneLength: [10, 11], flag: '🇳🇬' },
  { name: 'North Korea', code: 'KP', phoneCode: '+850', phoneLength: [10], flag: '🇰🇵' },
  { name: 'North Macedonia', code: 'MK', phoneCode: '+389', phoneLength: [8], flag: '🇲🇰' },
  { name: 'Norway', code: 'NO', phoneCode: '+47', phoneLength: [8], flag: '🇳🇴' },
  { name: 'Oman', code: 'OM', phoneCode: '+968', phoneLength: [8], flag: '🇴🇲' },
  { name: 'Pakistan', code: 'PK', phoneCode: '+92', phoneLength: [10], flag: '🇵🇰' },
  { name: 'Palau', code: 'PW', phoneCode: '+680', phoneLength: [7], flag: '🇵🇼' },
  { name: 'Panama', code: 'PA', phoneCode: '+507', phoneLength: [8], flag: '🇵🇦' },
  { name: 'Papua New Guinea', code: 'PG', phoneCode: '+675', phoneLength: [8], flag: '🇵🇬' },
  { name: 'Paraguay', code: 'PY', phoneCode: '+595', phoneLength: [9], flag: '🇵🇾' },
  { name: 'Peru', code: 'PE', phoneCode: '+51', phoneLength: [9], flag: '🇵🇪' },
  { name: 'Philippines', code: 'PH', phoneCode: '+63', phoneLength: [10], flag: '🇵🇭' },
  { name: 'Poland', code: 'PL', phoneCode: '+48', phoneLength: [9], flag: '🇵🇱' },
  { name: 'Portugal', code: 'PT', phoneCode: '+351', phoneLength: [9], flag: '🇵🇹' },
  { name: 'Qatar', code: 'QA', phoneCode: '+974', phoneLength: [8], flag: '🇶🇦' },
  { name: 'Romania', code: 'RO', phoneCode: '+40', phoneLength: [9], flag: '🇷🇴' },
  { name: 'Russia', code: 'RU', phoneCode: '+7', phoneLength: [10], flag: '🇷🇺' },
  { name: 'Rwanda', code: 'RW', phoneCode: '+250', phoneLength: [9], flag: '🇷🇼' },
  { name: 'Saint Kitts and Nevis', code: 'KN', phoneCode: '+1', phoneLength: [10], flag: '🇰🇳' },
  { name: 'Saint Lucia', code: 'LC', phoneCode: '+1', phoneLength: [10], flag: '🇱🇨' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', phoneCode: '+1', phoneLength: [10], flag: '🇻🇨' },
  { name: 'Samoa', code: 'WS', phoneCode: '+685', phoneLength: [7], flag: '🇼🇸' },
  { name: 'San Marino', code: 'SM', phoneCode: '+378', phoneLength: [10], flag: '🇸🇲' },
  { name: 'Sao Tome and Principe', code: 'ST', phoneCode: '+239', phoneLength: [7], flag: '🇸🇹' },
  { name: 'Saudi Arabia', code: 'SA', phoneCode: '+966', phoneLength: [9], flag: '🇸🇦' },
  { name: 'Senegal', code: 'SN', phoneCode: '+221', phoneLength: [9], flag: '🇸🇳' },
  { name: 'Serbia', code: 'RS', phoneCode: '+381', phoneLength: [9], flag: '🇷🇸' },
  { name: 'Seychelles', code: 'SC', phoneCode: '+248', phoneLength: [7], flag: '🇸🇨' },
  { name: 'Sierra Leone', code: 'SL', phoneCode: '+232', phoneLength: [8], flag: '🇸🇱' },
  { name: 'Singapore', code: 'SG', phoneCode: '+65', phoneLength: [8], flag: '🇸🇬' },
  { name: 'Slovakia', code: 'SK', phoneCode: '+421', phoneLength: [9], flag: '🇸🇰' },
  { name: 'Slovenia', code: 'SI', phoneCode: '+386', phoneLength: [8], flag: '🇸🇮' },
  { name: 'Solomon Islands', code: 'SB', phoneCode: '+677', phoneLength: [7], flag: '🇸🇧' },
  { name: 'Somalia', code: 'SO', phoneCode: '+252', phoneLength: [8], flag: '🇸🇴' },
  { name: 'South Africa', code: 'ZA', phoneCode: '+27', phoneLength: [9], flag: '🇿🇦' },
  { name: 'South Korea', code: 'KR', phoneCode: '+82', phoneLength: [10, 11], flag: '🇰🇷' },
  { name: 'South Sudan', code: 'SS', phoneCode: '+211', phoneLength: [9], flag: '🇸🇸' },
  { name: 'Spain', code: 'ES', phoneCode: '+34', phoneLength: [9], flag: '🇪🇸' },
  { name: 'Sri Lanka', code: 'LK', phoneCode: '+94', phoneLength: [9], flag: '🇱🇰' },
  { name: 'Sudan', code: 'SD', phoneCode: '+249', phoneLength: [9], flag: '🇸🇩' },
  { name: 'Suriname', code: 'SR', phoneCode: '+597', phoneLength: [7], flag: '🇸🇷' },
  { name: 'Sweden', code: 'SE', phoneCode: '+46', phoneLength: [9], flag: '🇸🇪' },
  { name: 'Switzerland', code: 'CH', phoneCode: '+41', phoneLength: [9], flag: '🇨🇭' },
  { name: 'Syria', code: 'SY', phoneCode: '+963', phoneLength: [9], flag: '🇸🇾' },
  { name: 'Taiwan', code: 'TW', phoneCode: '+886', phoneLength: [9], flag: '🇹🇼' },
  { name: 'Tajikistan', code: 'TJ', phoneCode: '+992', phoneLength: [9], flag: '🇹🇯' },
  { name: 'Tanzania', code: 'TZ', phoneCode: '+255', phoneLength: [9], flag: '🇹🇿' },
  { name: 'Thailand', code: 'TH', phoneCode: '+66', phoneLength: [9], flag: '🇹🇭' },
  { name: 'Togo', code: 'TG', phoneCode: '+228', phoneLength: [8], flag: '🇹🇬' },
  { name: 'Tonga', code: 'TO', phoneCode: '+676', phoneLength: [7], flag: '🇹🇴' },
  { name: 'Trinidad and Tobago', code: 'TT', phoneCode: '+1', phoneLength: [10], flag: '🇹🇹' },
  { name: 'Tunisia', code: 'TN', phoneCode: '+216', phoneLength: [8], flag: '🇹🇳' },
  { name: 'Turkey', code: 'TR', phoneCode: '+90', phoneLength: [10], flag: '🇹🇷' },
  { name: 'Turkmenistan', code: 'TM', phoneCode: '+993', phoneLength: [8], flag: '🇹🇲' },
  { name: 'Tuvalu', code: 'TV', phoneCode: '+688', phoneLength: [7], flag: '🇹🇻' },
  { name: 'Uganda', code: 'UG', phoneCode: '+256', phoneLength: [9], flag: '🇺🇬' },
  { name: 'Ukraine', code: 'UA', phoneCode: '+380', phoneLength: [9], flag: '🇺🇦' },
  { name: 'United Arab Emirates', code: 'AE', phoneCode: '+971', phoneLength: [9], flag: '🇦🇪' },
  { name: 'United Kingdom', code: 'GB', phoneCode: '+44', phoneLength: [10, 11], flag: '🇬🇧' },
  { name: 'United States', code: 'US', phoneCode: '+1', phoneLength: [10], flag: '🇺🇸' },
  { name: 'Uruguay', code: 'UY', phoneCode: '+598', phoneLength: [8], flag: '🇺🇾' },
  { name: 'Uzbekistan', code: 'UZ', phoneCode: '+998', phoneLength: [9], flag: '🇺🇿' },
  { name: 'Vanuatu', code: 'VU', phoneCode: '+678', phoneLength: [7], flag: '🇻🇺' },
  { name: 'Vatican City', code: 'VA', phoneCode: '+379', phoneLength: [10], flag: '🇻🇦' },
  { name: 'Venezuela', code: 'VE', phoneCode: '+58', phoneLength: [10], flag: '🇻🇪' },
  { name: 'Vietnam', code: 'VN', phoneCode: '+84', phoneLength: [9, 10], flag: '🇻🇳' },
  { name: 'Yemen', code: 'YE', phoneCode: '+967', phoneLength: [9], flag: '🇾🇪' },
  { name: 'Zambia', code: 'ZM', phoneCode: '+260', phoneLength: [9], flag: '🇿🇲' },
  { name: 'Zimbabwe', code: 'ZW', phoneCode: '+263', phoneLength: [9], flag: '🇿🇼' }
];

// Helper function to get country by code
export const getCountryByCode = (code: string): Country | undefined => {
  return countries.find(country => country.code === code);
};

// Helper function to get country by name
export const getCountryByName = (name: string): Country | undefined => {
  return countries.find(country => country.name === name);
};

// Helper function to validate phone number for a specific country
export const validatePhoneNumber = (phoneNumber: string, country: Country): boolean => {
  const cleanNumber = phoneNumber.replace(/\D/g, '');
  return country.phoneLength.some(length => cleanNumber.length === length);
};

// Helper function to format phone number with country code
export const formatPhoneNumber = (phoneNumber: string, country: Country): string => {
  const cleanNumber = phoneNumber.replace(/\D/g, '');
  return `${country.phoneCode} ${cleanNumber}`;
};
