name: rnz_cropwise_flutter
description: "RNZ CropWise - Smart Farming Mobile App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # HTTP Client
  dio: ^5.4.0
  http: ^1.1.0

  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Biometric Authentication
  local_auth: ^2.1.8

  # UI Components
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  lottie: ^2.7.0
  shimmer: ^3.0.0

  # Image & File Handling
  image_picker: ^1.0.4
  path_provider: ^2.1.1

  # Location & Permissions
  geolocator: ^14.0.2
  geocoding: ^3.0.0
  permission_handler: ^12.0.1

  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.2.1
  package_info_plus: ^8.3.1
  device_info_plus: ^11.5.0

  # PDF & Charts
  syncfusion_flutter_pdfviewer: ^30.2.7
  fl_chart: ^1.1.0

  # Form Validation
  form_validator: ^2.1.1

  # JSON Serialization
  json_annotation: ^4.8.1

  # Connectivity
  connectivity_plus: ^6.1.5

  # WebView
  webview_flutter: ^4.4.2

  # QR Code
  qr_flutter: ^4.1.0

  # Share
  share_plus: ^11.1.0

  # Local Notifications
  flutter_local_notifications: ^19.4.1

  # App Icons
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/rnz_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/rnz_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/rnz_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/rnz_logo.png"
